"""
Report Generator for AI Accessibility Testing Agent
Generates comprehensive reports in various formats
"""

import json
import html
from typing import Dict, List, Any
from datetime import datetime

class ReportGenerator:
    """Generates accessibility test reports in various formats"""
    
    def __init__(self):
        pass
    
    def generate_html_report(self, report_data: Dict[str, Any]) -> str:
        """Generate an HTML report from the report data"""
        html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Accessibility Test Report</title>
    <style>
        body {{ 
            font-family: 'Segoe UI', Arial, sans-serif; 
            margin: 0; 
            padding: 20px; 
            background: #f5f5f5; 
        }}
        .container {{ 
            max-width: 1200px; 
            margin: 0 auto; 
            background: white; 
            padding: 30px; 
            border-radius: 8px; 
            box-shadow: 0 2px 10px rgba(0,0,0,0.1); 
        }}
        .header {{ 
            border-bottom: 3px solid #007acc; 
            padding-bottom: 20px; 
            margin-bottom: 30px; 
        }}
        .score {{ 
            font-size: 2.5em; 
            font-weight: bold; 
            color: {self._get_score_color(report_data['summary']['compliance_score'])}; 
        }}
        .severity-critical {{ color: #d32f2f; font-weight: bold; }}
        .severity-high {{ color: #f57c00; font-weight: bold; }}
        .severity-medium {{ color: #fbc02d; font-weight: bold; }}
        .severity-low {{ color: #388e3c; }}
        .severity-info {{ color: #1976d2; }}
        .issue-card {{ 
            border: 1px solid #ddd; 
            margin: 10px 0; 
            padding: 15px; 
            border-radius: 4px; 
            background: #fafafa; 
        }}
        .agent-section {{ 
            margin: 20px 0; 
            padding: 15px; 
            border-left: 4px solid #007acc; 
            background: #f8f9fa; 
        }}
        .recommendation {{ 
            padding: 15px; 
            margin: 20px 0; 
            border-radius: 4px; 
            background: #e3f2fd; 
            border-left: 4px solid #2196f3; 
        }}
        table {{ 
            width: 100%; 
            border-collapse: collapse; 
            margin: 15px 0; 
        }}
        th, td {{ 
            padding: 10px; 
            text-align: left; 
            border-bottom: 1px solid #ddd; 
        }}
        th {{ background: #f5f5f5; }}
        .wcag-guideline {{ 
            background: #e8f5e8; 
            padding: 2px 6px; 
            border-radius: 3px; 
            font-size: 0.9em; 
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🤖 AI Accessibility Test Report</h1>
            <p><strong>URL:</strong> {html.escape(report_data['metadata']['url'])}</p>
            <p><strong>Test Date:</strong> {report_data['metadata']['test_date']}</p>
            <p><strong>WCAG Version:</strong> {report_data['metadata']['wcag_version']}</p>
            <div class="score">Compliance Score: {report_data['summary']['compliance_score']}/100</div>
        </div>
        
        <div class="recommendation">
            <h3>🎯 Priority Recommendation</h3>
            <p>{html.escape(report_data['summary']['recommendation'])}</p>
        </div>
        
        <h2>📊 Summary</h2>
        <table>
            <tr><th>Severity</th><th>Count</th></tr>
            {self._generate_severity_table_rows(report_data['summary']['severity_breakdown'])}
        </table>
        
        <h2>🤖 Agent Results</h2>
        {self._generate_agent_sections(report_data['agent_results'])}
        
        <h2>📋 Issues by Severity</h2>
        {self._generate_issues_by_severity(report_data['issues_by_severity'])}
        
        <h2>📖 WCAG Guidelines</h2>
        {self._generate_wcag_sections(report_data['issues_by_wcag_guideline'])}
        
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 0.9em;">
            Report generated by AI Accessibility Testing Agent v1.0 on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </div>
</body>
</html>
"""
        return html_content
    
    def _get_score_color(self, score: int) -> str:
        """Get color based on compliance score"""
        if score >= 90:
            return "#4caf50"  # Green
        elif score >= 70:
            return "#ff9800"  # Orange
        else:
            return "#f44336"  # Red
    
    def _generate_severity_table_rows(self, severity_breakdown: Dict[str, int]) -> str:
        """Generate table rows for severity breakdown"""
        rows = []
        severity_colors = {
            'critical': 'severity-critical',
            'high': 'severity-high',
            'medium': 'severity-medium',
            'low': 'severity-low',
            'info': 'severity-info'
        }
        
        for severity, count in severity_breakdown.items():
            color_class = severity_colors.get(severity, '')
            rows.append(f'<tr><td class="{color_class}">{severity.title()}</td><td>{count}</td></tr>')
        
        return '\\n'.join(rows)
    
    def _generate_agent_sections(self, agent_results: Dict[str, Any]) -> str:
        """Generate sections for each agent's results"""
        sections = []
        for agent_name, results in agent_results.items():
            section = f"""
            <div class="agent-section">
                <h3>{html.escape(agent_name)}</h3>
                <p><strong>Issues Found:</strong> {results['issues_found']}</p>
                <div>
                    {self._generate_severity_breakdown_inline(results['severity_breakdown'])}
                </div>
            </div>
            """
            sections.append(section)
        
        return '\\n'.join(sections)
    
    def _generate_severity_breakdown_inline(self, breakdown: Dict[str, int]) -> str:
        """Generate inline severity breakdown"""
        items = []
        for severity, count in breakdown.items():
            if count > 0:
                items.append(f'<span class="severity-{severity}">{severity.title()}: {count}</span>')
        
        return ' | '.join(items) if items else 'No issues found'
    
    def _generate_issues_by_severity(self, issues_by_severity: Dict[str, List[Dict]]) -> str:
        """Generate issues grouped by severity"""
        sections = []
        
        for severity in ['critical', 'high', 'medium', 'low', 'info']:
            issues = issues_by_severity.get(severity, [])
            if issues:
                section = f"""
                <h3 class="severity-{severity}">{severity.title()} Issues ({len(issues)})</h3>
                {self._generate_issue_cards(issues)}
                """
                sections.append(section)
        
        return '\\n'.join(sections)
    
    def _generate_issue_cards(self, issues: List[Dict[str, Any]]) -> str:
        """Generate issue cards"""
        cards = []
        
        for issue in issues:
            wcag_badge = f'<span class="wcag-guideline">{html.escape(issue["wcag_guideline"])}</span>' if issue.get("wcag_guideline") else ''
            selector_info = f'<p><strong>Element:</strong> <code>{html.escape(issue["element_selector"])}</code></p>' if issue.get("element_selector") else ''
            fix_info = f'<p><strong>Suggested Fix:</strong> {html.escape(issue["suggested_fix"])}</p>' if issue.get("suggested_fix") else ''
            
            card = f"""
            <div class="issue-card">
                <h4>{html.escape(issue['issue_type'])} {wcag_badge}</h4>
                <p><strong>Agent:</strong> {html.escape(issue['agent_name'])}</p>
                <p><strong>Description:</strong> {html.escape(issue['description'])}</p>
                {selector_info}
                {fix_info}
            </div>
            """
            cards.append(card)
        
        return '\\n'.join(cards)
    
    def _generate_wcag_sections(self, issues_by_wcag: Dict[str, List[Dict]]) -> str:
        """Generate sections for WCAG guidelines"""
        if not issues_by_wcag:
            return '<p>No WCAG guideline violations found.</p>'
        
        sections = []
        for guideline, issues in issues_by_wcag.items():
            section = f"""
            <div class="agent-section">
                <h3>{html.escape(guideline)} ({len(issues)} issues)</h3>
                {self._generate_issue_cards(issues)}
            </div>
            """
            sections.append(section)
        
        return '\\n'.join(sections)
